[package]
name = "asstosrt_wasm"
version = "0.1.0"
authors = ["sorz <orz@sorz.org>"]
edition = "2021"

[dependencies]
stdweb = "0.4.20"
regex = "1"
lazy_static = "1"
encoding = "0.2"
chardet = "0.2"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
simplecc = "0.2"
crc = "1.8.1"
