[package]
name = "asstosrt_wasm"
version = "0.1.0"
authors = ["sorz <orz@sorz.org>"]
edition = "2024"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
leptos = { version = "0.7", features = ["csr", "nightly"] }
leptos_meta = { version = "0.7" }
leptos_router = { version = "0.7", features = ["nightly"] }
reactive_stores = "0.1"
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "console",
    "Blob", "BlobPropertyBag",
    "File", "FileList", "FileReaderSync",
    "DataTransfer", "DataTransferItem", "DataTransferItemList",
    "DedicatedWorkerGlobalScope", "Worker", "WorkerOptions", "WorkerType",
] }
js-sys = { version = "0.3" }
regex = "1"
uuid = { version = "1", features = ["v4", "js"] }
futures = "0.3"
send_wrapper = "0.6"
lazy_static = "1"
encoding = "0.2"
chardet = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1"
strum = { version = "0.27", features = ["derive"] }
simplecc = "0.2"
crc = "3"
