[package]
name = "asstosrt_wasm"
version = "0.1.0"
authors = ["sorz <orz@sorz.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console", "Blob", "BlobPropertyBag"] }
js-sys = { version = "0.3" }
regex = "1"
lazy_static = "1"
encoding = "0.2"
chardet = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1"
simplecc = "0.2"
crc = "3"
