[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true


[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false

[[hooks]]
stage = "post_build"
command = "uv"
command_arguments = ["run", "--script", "scripts/hash_worker.py"]